export default (commonData = {
 
   string_constants:{
     sign_in:"Sign In",
     sing_out:"Sign Up",
     app_name: "LAPARED",
     login:"Login",
     enter_email:`Enter your email address and password \n to get access your account`,
     logo_name: "A WALL OF PRIVACY",
    forgot_password : "Forgot password",
    please_enter_email:"Please enter your registered email and \n we'll send you a link to reset your password",
    wait_message:"Wait , I remember my password.",
    licence_date : "@2020 Lapared , LLC",
    check_email:"Check you email",
    send_password_message:"We have sent you a reset password link \n on your registered email address.",
    create_new_password:"Create new password",
    enter_password:"Enter new password.",
    password_chamged: "Password changed",
    you_can_now :"You can now use your new password to \n login in to your account!",
    terms_of_service:"Terms of Service",
    date_and_time:"Last update April 2020",
    my_service:" 1. Using our services",
    your_account: "2. Your Account",
    callencation_policy:"3. Cancellation Policy",
    money_back:"4. Money Back Guarantee",
    lorem_ipsum : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    lorem_ipsum22 : "Lorem ipsum dolor sit amet, consectetur   idipiscing elit, sed do eiusmod tempor  consectetur adipiscing elit, adipiscing elit, idipiscing elit, sed do eiusmod tempor  consectetur adipiscing elit, idipiscing elit, sed do eiusm  incididunt ut labore et dolore magna aliqua.",
    add_to_story: " Add to \n Your 24 Live" ,
    by_creating_newaccount:"By creating new account you agree to the",
    terms_use:'terms of use',
    and_our:'and our',
    privacy_policy:'privacy policy.',
    AlreadyHaveAnAccount:'Already have an account?',
  

   },

  ToastMessages: {
    PasswordDoesntMatch:`Password entries do not match`,
    Atleastcharactersnumberuppercaseletterlowercaseletteronespecialcharacter:'Password entry does not meet criteria',
    InvaildEmail:'Invaild Email!',
    Pleasefillallrequiredfields:'Cannot Be Empty',
    no_internet: "No internet connectivity detected. Please try again.",
    no_name: "Please enter name.",
    no_email: "Please enter email.",
    no_number: "Please enter mobile number.",
    valid_email: "Please enter valid email.",
    valid_number: "Please enter Valid mobile number.",
    no_age: "Please enter your age.",
    no_gender: "Please select your gender.",
    accept_condition: "Please accept terms and policies.",
  },
  api_endpoint: {
    signup: "Common_API/patientSaveV2",
    search: "patient/searchDoctors_app",
    verify: "Common_API/patient_signinV2/",
    otp_verify_signup: "index/verifypatientSigninotpv2",
    otp_verify: "index/verifypatientSigninotp",
    resend_otp: "index/sendpatientOtpv2",
    book_appointment: "Common_API/bookAppointmentByPatient",
    get_prescriptions: 'index.php/Common_API/doctorPrescription/',
    Prescription_detail: 'index.php/Common_API/doctorDescription/',
    getMyDoctor: "index.php/Common_API/getMyDoctorsList/",
    getAllPayments: "index.php/Common_API/getAllPayments/",
    getReminderNotification: "index.php/Common_API/getReminderNotification",
    updateReminderNotification: "index.php/Common_API/updateReminderNotification",
    viewDoctorNumber: "index.php/Common_API/saveViewDoctorNumber",
    getCities: 'Common_API/getClinicCities',
    rateDoctor: 'index.php/Common_API/addFeedback',
    aboutUs: "index.php/Common_API/page/28",
    privacy_policy: 'index.php/Common_API/page/109',
    terms_and_conditions: "index.php/Common_API/page/30",
    FAQS: "index.php/Common_API/page/108",
    doctor_favourite: "index.php/Common_API/doctorFavorite",

  },
  regex: {
    firstname: /^[a-zA-Z ]*$/,
    email: /^[a-zA-Z][a-zA-Z0-9_+]*(\.[a-zA-Z][a-zA-Z0-9_]*)?@[a-z][a-zA-Z-0-9]*\.[a-z]+(\.[a-z]+)?$/,
    mobile_number: /^[A-Za-z]\w{6,14}$/,
  },
  doctor: {
    name: "",
    doctor_id: "",
    details: "",
  },
  status:{
    code:401
  }
});
