const images = {
    back:require('../../assests/image/back.png'),
    common_background:require('../../assests/image/login_background.png'),
    introhome:require('../../assests/image/introhome.png'),
    company_logo:require('../../assests/image/company_logo.png'),
    notification:require('../../assests/image/bell.png'),
    search:require('../../assests/image/search.png'),
    user_profileimage:require('../../assests/image/user_profileimage.png'),
    video_icon:require('../../assests/image/video.png'),
    shotButton:require('../../assests/image/shotButton.png'),
    messageStory:require('../../assests/image/messageStory.png'),
    shotButtonRed:require('../../assests/image/shotButtonRed.png'),
    post_icon:require('../../assests/image/post.png'),
    post_photo:require('../../assests/image/photo.png'),
    right_arrow:require('../../assests/image/arrow_right.png'),
    left_arrow:require('../../assests/image/arrow_left.png'),
    building:require('../../assests/image/building.png'),
    add_story:require('../../assests/image/add_story.png'),
    second_story:require('../../assests/image/second_story.png'),
    group_image:require('../../assests/image/group_image.png'),
    more_options:require('../../assests/image/more.png'),
    delete_icon:require('../../assests/image/delete.png'),
    add:require('../../assests/image/add.png'),
    img1:require('../../assests/image/img1.png'),
    img2:require('../../assests/image/img2.png'),
    tick:require('../../assests/image/tick.png'),
    one:require('../../assests/image/1.png'),
    two:require('../../assests/image/2.png'),
    three:require('../../assests/image/3.png'),
    four:require('../../assests/image/4.png'),
    five:require('../../assests/image/5.png'),
    six:require('../../assests/image/6.png'),
    seven:require('../../assests/image/7.png'),
    statusGreen:require('../../assests/image/status-active.png'),
    visibilitygroup:require('../../assests/image/visibilitygroup.png'),
    addfriend:require('../../assests/image/addfriend.png'),
    profile:require('../../assests/image/profile.png'),
    setting:require('../../assests/image/setting.png'),
    location:require('../../assests/image/location.png'),
    Community:require('../../assests/image/community.png'),
    Group:require('../../assests/image/Group.png'),
    EllipseRed:require('../../assests/image/Ellipsered.png'),
    EllipseGray:require('../../assests/image/Ellipsegray.png'),
    emojiAngry:require('../../assests/image/emoji-angry.png'),
    emojiClap:require('../../assests/image/emoji-clap.png'),
    emojiHappy:require('../../assests/image/emoji-happy.png'),
    emojiLaughing:require('../../assests/image/emoji-laughing.png'),
    communityStoryBack:require('../../assests/image/communityStoryBack.png'),
    comments:require('../../assests/image/comments.png'),
    share:require('../../assests/image/share.png'),
    cross:require('../../assests/image/cross.png'),
    dummyPerson:require('../../assests/image/dummy-person.png'),
    bin:require('../../assests/image/bin.png'),
    logout:require('../../assests/image/leave-logout.png'),
    dummyCommunityStories:require('../../assests/image/dummyCommunityStories.png'),
    tabchatA:require('../../assests/image/tabchatA.png'),
    tabchatN:require('../../assests/image/tabchatN.png'),
    tabcommunitA:require('../../assests/image/tabcommunitA.png'),
    tabcommunitN:require('../../assests/image/tabcommunityN.png'),
    tabhomeA:require('../../assests/image/tabhomeA.png'),
    tabhomeN:require('../../assests/image/tabhomeN.png'),
    tabprofileA:require('../../assests/image/tabprofileA.png'),
    tabprofileN:require('../../assests/image/tabprofileN.png'),
    tabshoppingA:require('../../assests/image/tabshoppingA.png'),
    tabshoppingN:require('../../assests/image/tabshoppingN.png'),
    logo:require('../../assests/image/Logo.png'),
    copylink:require('../../assests/image/copylink.png'),
    locationaddress:require('../../assests/image/locationaddress.png'),
    edit:require('../../assests/image/edit.png'),
    Groupmsg:require('../../assests/image/Groupmsg.png'),
    hide:require('../../assests/image/hide.png'),
    share:require('../../assests/image/share.png'),
    unfriend:require('../../assests/image/unfriend.png'),
    cameraupload:require('../../assests/image/cameraupload.png'),
    Vector:require('../../assests/image/Vector.png'),
    menu:require('../../assests/image/menu.png'),
    refresh:require('../../assests/image/refresh.png'),
    addfriendProfile:require('../../assests/image/addfriendProfile.png'),
    commentsProfile:require('../../assests/image/commentsProfile.png'),
    editProfile:require('../../assests/image/editProfile.png'),
    deleteIcon: require('../../assests/image/camera/delete.png'),
    camerachange2: require('../../assests/image/camera/camerachange2.png'),
    photoLighteffect2: require('../../assests/image/camera/photo-lighteffect2.png'),
    setting2: require('../../assests/image/camera/setting2.png'),
    laparedlogo: require('../../assests/image/laparedlogo.png'),
    dropDown:  require('../../assests/image/dropDown.png'),
    selectCommunity : require('../../assests/image/selectCommunity.png'),
    storyViewers : require('../../assests/image/story.png'),
    setting2 : require('../../assests/image/setting2.png'),
    Rectangle8 : require('../../assests/image/Rectangle8.png'),
    plusCircle : require('../../assests/image/Group17.png'),
    passwordShow : require('../../assests/image/password-show.png'),
    showEye: require('../../assests/image/show.png'),

}

export default images;