export const GETHOME_REQUEST = 'GetHome/GETHOME_REQUEST';
export const GETHOME_SUCCESS = 'GetHome/GETHOME_SUCCESS';
export const GETHOME_FAILURE = 'GetHome/GETHOME_FAILURE';

export const GET_STORIES_SUCCESS = 'GETSTORIES/GET_STORIES_SUCCESS';
export const GET_COMMUNITY_SUCCESS = 'GETSTORIES/GET_COMMUNITY_SUCCESS';
export const GET_CONTACTS_SUCCESS = 'GETSTORIES/GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILED = 'GETSTORIES/GET_CONTACTS_FAILED';
export const GET_STORIES_FAILED = 'GETSTORIES/GET_STORIES_FAILED';
export const GET_STORIES_REQUEST = 'GETSTORIES/GET_STORIES_REQUEST';

export type State = {
  error: string | null
};
